### ISSUE TITLE
Coinbase & Binance (i.e.) not working after few minutes

### ISSUE THREAD

**Issue by ftso-eu** [mouradski/ftso-prices-aggregator#18]
**App not sending data"

Trades or Tickers from Binance or Coinbase (i.e.) are not coming (branch main)

**Comment by JamesGDiaz** [comment]
I think #22 fixes this, could you please check?

**Comment by ftso-eu** [comment]
yep it seems solved for them, but still not for kucoin

**Comment by JamesGDiaz** [comment]
Do you not see anything at all from kucoin or bittrex? 
What happens if you set `EXCHANGES=kucoin,bittrex` only?

I dont have any problem with any of those exchanges

**Comment by ftso-eu** [comment]
kucoin is ok (my fault) while bittrex seems broken speaking about the ticker endpoint
pulled from main
